package com.qaplus.constant;

public enum ExcelPrimaryKey {
	//
	DOWNLOAD_EXAM_QUESTION_TEMPLATE,
	//
	DOWNLOAD_T_QUESTION_TEMPLATE,
	//
	EXPORT_EXAM_QUESTION,
	//
	EXPORT_T_QUESTION_TEMPLATE,
	//
	TEST_GET_CRON_FROM_DB;
}
